Time request
Lokideos/rack_time pull request #1
Opened 2018-11-27 14:48 UTC by Lokideos

В рамках данного пул реквеста был реализован следующий функционал:
1) Пользователь может отправлять запросы на сервер и получать ответ в виде текущего времени в интересующем его формате;
2) В случае отправки запроса не туда, пользователю отправляется ответ с статусом 404;
3) В случае отправки запроса не с теми параметрами (e.g.: с несуществующем типом временных единиц), пользователю отправляется ответ с статусом 400.

2018-11-29 10:08 UTC, psylone requested changes

2018-11-29 10:08 UTC, psylone commented on app.rb
> +      [status_404, headers, body]
Лучше сделать отдельный метод, например, `not_found_response`.

2018-11-29 10:08 UTC, psylone commented on app.rb
> +      show_time(env["QUERY_STRING"])
Стоит мыслить в терминах ответа, то есть `time_response`, вместо `show_time`.

2018-11-29 10:08 UTC, psylone commented on app.rb
> +      show_time(env["QUERY_STRING"])
Используй объекты классов `Rack::Request` и `Rack::Response`, чтобы удобнее работать с параметрами и формированием ответа.

2018-11-29 10:08 UTC, psylone commented on app.rb
> +  end
Если ты укажешь `200` вместо вызова `status_200` ничего не изменится. Метод имел бы смысл, если бы его содержание могло меняться, но статус `200` вряд ли изменится.

2018-11-29 10:08 UTC, psylone commented on app.rb
> +  def show_time(query)
Смотри, у тебя есть класс Rack приложения который должен заниматься обработкой запроса и формированием ответа. И есть другая абстракция - класс который ничего не знает про Rack и вообще о том где он используется. Его задача - получить строку с форматом времени и преобразовать её. Поэтому всю логику форматирования времени стоит поместить в отдельный класс.

2018-12-01 19:31 UTC, BubuntuClu commented on application/time_calculator.rb
> +    return ("Unkown time format: #{unknown_formats}\n") if unknown_formats.length > 0
можно так `unknown_formats.any?`

2018-12-01 19:31 UTC, BubuntuClu commented on app.rb
> +    [200, body]
если будут неизвестные форматы, то у тебя код ответа будет 200, с перечислением неизвестных форматов, а в задаче надо вернуть 400 код

2018-12-02 09:57 UTC, Lokideos commented on app.rb
> +    [200, body]
Поправил

2018-12-02 09:57 UTC, Lokideos commented on application/time_calculator.rb
> +    return ("Unkown time format: #{unknown_formats}\n") if unknown_formats.length > 0
Поправил

2018-12-02 12:22 UTC, psylone approved these changes

2018-12-02 12:22 UTC, psylone commented on app.rb
> +      response.body = not_found_response.last
Я бы вызывал `not_found_response(response)` и внутри метода уже устанавливал `status` и `body`.

2018-12-02 12:22 UTC, psylone commented on app.rb
> +    body = []
Используй `request.params`, жизнь станет немного проще.

2018-12-02 12:22 UTC, psylone commented on app.rb
> +    calculator = TimeCalculator.new(time)
Сюда можно передавать сразу строку формата: `request.params['format']`.

2018-12-02 12:22 UTC, psylone commented on app.rb
> +    return [400, bad_query] unless query[0..6] == FORMAT_QUERY_BEGIN
Условие можно вынести в приватный метод.

2018-12-02 12:22 UTC, psylone commented on app.rb
> +    [200, body]
Было бы удобней использовать условное выражение, что-то вроде:

```ruby
calculator = TimeCalculator.new(time)

if calculator.success?
else
end
```

2018-12-02 22:58 UTC, Lokideos commented
@psylone надеюсь, что я правильно понял насчет последнего коммента (правда, я проверку в тернарный оператор вынес).

2018-12-02 22:59 UTC, merged